### ISSUE TITLE
Vagabond package looking for a new home

### ISSUE THREAD

**Issue by ali-ramadhan** [CBIOMES/Community#1]
Not sure if this CBIOMES organization has a specific purpose or if it's meant to house various related repositories, but if you're accepting related packages then I was wondering if this organization would be a good place to put a package like https://github.com/ali-ramadhan/lagrangian-microbes

**Comment by gaelforget** [comment]
Hi @ali-ramadhan 

Planned next step for this organization is to consult Cbiomes folks and decide how we want to use this. Should take place in the spring.

I might suggest https://github.com/darwinproject instead which @jahn operates for the MIT group. 

Would this work?

**Comment by ali-ramadhan** [comment]
Ah thank you for the clarification!

Either organization sounds great. I am hoping to put it somewhere more visible but maybe I shouldn't do that until I can actively maintain it.
